// Each step sets the cooker mode (heat, sealed, blocked) and a starting water temperature.
export const COOKER_STORY = [
  { t: 'Water and food go in the pot', part: 'Pot · Water · Chickpeas', explode: 0, focus: ['pot', 'water', 'food'], cut: true,
    heat: false, sealed: false, startT: 25,
    d: 'A 5 litre aluminium pot holds the food and some water. Fill it no more than two-thirds, so the steam has space to collect above the water.' },
  { t: 'A rubber gasket seals the lid', part: 'Lid · Gasket', explode: 0.4, focus: ['lid', 'gasket'], cut: false,
    heat: false, sealed: true, startT: 25,
    d: 'The lid locks under the rim of the pot. A rubber gasket fills the gap between them, so steam cannot leak out at the edge. Now the only way out is the vent pipe.' },
  { t: 'The flame heats the water', part: 'Burner · Water', explode: 0, focus: ['burner', 'water'], cut: true,
    heat: true, sealed: true, startT: 60,
    d: 'In an open pot, water boils at 100°C and stays there. Extra heat only makes more steam, and the steam escapes into the room.' },
  { t: 'Trapped steam raises the pressure', part: 'Steam · Lid', explode: 0, focus: ['water', 'lid'], cut: true,
    heat: true, sealed: true, startT: 100,
    d: 'In the sealed cooker the steam has nowhere to go. More steam in the same space means more pressure. Watch the reading climb above zero.' },
  { t: 'Higher pressure makes hotter water', part: 'Water · Chickpeas', explode: 0, focus: ['water', 'food'], cut: true,
    heat: true, sealed: true, startT: 108,
    d: 'Pressure pushes back on the water, so it needs more heat to boil. At 1 bar above normal air pressure, water boils at about 120°C. Food cooks about three times faster at that temperature.' },
  { t: 'The weight lifts and whistles', part: 'Whistle weight · Vent pipe', explode: 0, focus: ['weight', 'vent'], cut: false,
    heat: true, sealed: true, startT: 116,
    d: 'A 100 g weight sits on a 3.5 mm vent pipe. Steam lifts it when the pressure reaches weight ÷ area: about 1 bar. Steam rushes out and whistles, the pressure drops a little, and the weight falls back. Cooks count the whistles.' },
  { t: 'A safety valve is the backup', part: 'Safety valve', explode: 0.3, focus: ['safety'], cut: false,
    heat: true, sealed: true, blocked: true, startT: 116,
    d: 'If food blocks the vent, the weight cannot lift and the pressure keeps rising. At about 2 bar the safety valve opens and lets the steam out before the pot can fail.' },
  { t: 'Let it cool before you open it', part: 'Lid · Gasket', explode: 0, focus: ['lid', 'gasket'], cut: true,
    heat: false, sealed: true, cooling: true, startT: 118,
    d: 'Turn off the flame and wait. As the water cools, the steam condenses and the pressure falls to zero. Only then does the lid turn freely. Never force it open while it is under pressure.' },
];
