// cut: which shell turns see-through ('base' or 'jar'). view: the camera framing.
// magnets: show the stator's poles ('field'), the armature's poles too ('dc'), or both flipping on AC ('ac').
export const MIXER_STORY = [
  { t: 'The knob picks a speed', part: 'Speed switch · Knob', explode: 0, focus: ['knob'], cut: false, view: 'all',
    d: 'Mains power at 230 V comes in through the cord and goes to a rotary switch behind the knob. The switch has off, three speeds and a pulse setting that runs the motor only while you hold the knob. Each speed sends the current through a different length of the field coil.' },
  { t: 'Field coils make an electromagnet', part: 'Stator · Field coils', explode: 0, focus: ['stator'], cut: 'base', view: 'motor', magnets: 'field',
    d: 'The stator is a stack of thin iron sheets with a copper coil on each side. Current in the coils makes the iron a magnet: north on one side, south on the other. A spinning motor also works as a generator, and it speeds up until the voltage it makes nearly matches the supply. On speed 3 the current skips part of the coil. The field is weaker, so the motor must spin faster to make that voltage.' },
  { t: 'Brushes feed the spinning armature', part: 'Carbon brushes · Commutator · Armature', explode: 0.3, focus: ['brushes', 'commutator', 'armature'], cut: 'base', view: 'motor', magnets: 'dc',
    d: 'The armature is the part that spins: an iron core with copper coils in its slots. Two carbon brushes press on the commutator, a ring of copper bars at its end. As the shaft turns, each coil reaches the brushes and its current reverses. So the armature\'s own poles stay in the same place while it turns under them, and the stator pulls it round and round. Carbon is soft, so the brushes slowly wear down and need replacing.' },
  { t: 'AC flips both magnets at once', part: 'Field coils · Armature in series', explode: 0.5, focus: ['stator', 'armature'], cut: 'base', view: 'motor', magnets: 'ac',
    d: 'The field coils and the armature are wired in series, so one current flows through both. On 50 Hz mains that current reverses 100 times a second. Both magnets reverse at the same moment, so the pull still turns the armature the same way. That is why this is called a universal motor: it runs on AC or DC. Here the colours flip 100 times slower than in a real motor.' },
  { t: 'A fan cools the motor', part: 'Cooling fan · Thermal cut-out', explode: 0.2, focus: ['fan', 'overload'], cut: 'base', view: 'motor', air: true,
    d: 'A fan on the bottom of the shaft pulls air down through the motor and blows it out of the vents. At 750 W the coils still get hot with a heavy load. If they get too hot, a thermal cut-out opens the circuit and the motor stops. Let it cool, then press the red reset button under the base.' },
  { t: 'Couplers hand the spin to the jar', part: 'Motor coupler · Jar coupler', explode: 0, focus: ['coupler', 'jarCoupler'], cut: false, view: 'coupler', lift: true,
    d: 'The motor shaft ends in a star-shaped coupler on top of the base. The blade shaft under the jar has a matching one. Set the jar down and the teeth lock together. The couplers are rubber or nylon: they take the shock when the motor starts, and they wear out before the motor does. Lift the jar and the blades stop.' },
  { t: 'The blades spin at 18,000 rpm', part: 'Blades · Sealed bearings', explode: 0, focus: ['blades'], cut: 'jar', view: 'blades',
    d: 'Four stainless steel blades sit on a short shaft that turns in sealed bearings in the floor of the jar. Two wings bend up and two bend down, so they cut at two levels. At 18,000 rpm the tips of a 76 mm blade move at about 260 km/h. At that speed they smash the food as much as they cut it.' },
  { t: 'Ribs in the jar turn the food over', part: 'Jar · Flow breakers', explode: 0, focus: ['jar'], cut: 'jar', view: 'jar', food: true,
    d: 'The blades throw the food outward, and it climbs the wall of the jar. Without help it would spin around with the blades and never meet them again. Ribs on the inside wall break up that spin, so the food falls back down the middle into the blades. A full jar is a heavy load: the motor slows down and draws more current.' },
];
